/**
 * NutriAI — Curated Demo Data Store v2.0
 * Realistic, balanced nutritional information, recipes, food database,
 * biomarkers, nutrigenomics traits, and specialist network.
 * 
 * v2.0 Changes:
 * - All 28 meal plan entries tagged with allergenTags[]
 * - Extended defaultProfile with sleep, exerciseFrequency, mealFrequency,
 *   cuisinePreference, allergies[], restrictions[]
 * - Expanded foodDatabase to 30 entries with fiber field
 * - Added vegetarian/vegan alternative meal pools for filtering
 */

const NutriAIData = {
  // Demo User Profile
  defaultProfile: {
    name: "Alex Morgan",
    email: "alex.morgan@example.com",
    gender: "male",
    age: 28,
    height: 178, // cm
    weight: 74.2, // kg
    targetWeight: 71.0, // kg
    activityLevel: "moderate", // sedentary, light, moderate, high, athlete
    goal: "fat_loss", // fat_loss, maintenance, muscle_gain, recomposition
    dietPreference: "balanced", // balanced, vegetarian, vegan, keto, pescatarian
    sleep: 7.5, // hours target
    exerciseFrequency: "3_5", // 0, 1_2, 3_5, 6_7
    mealFrequency: 4, // meals per day: 2, 3, 4, 5, 6
    cuisinePreference: "mediterranean", // mediterranean, asian, american, indian, mixed
    allergies: ["Lactose Sensitive"],
    restrictions: [], // dairy, gluten, nuts, soy, eggs, shellfish
    waterTarget: 3200, // ml
    sleepTarget: 8.0 // hours
  },

  // 7-Day Meal Plan Database (Balanced / High Protein)
  // Each meal tagged with allergenTags for dietary filtering
  mealPlans: {
    Mon: [
      {
        id: "m1_1",
        type: "Breakfast",
        name: "Avocado & Poached Egg Protein Sourdough",
        calories: 420,
        protein: 24,
        carbs: 38,
        fats: 18,
        fiber: 8,
        prepTime: "12 min",
        category: "Produce / Dairy / Bakery",
        allergenTags: ["eggs", "gluten"],
        vegetarianSafe: true,
        veganSafe: false,
        ingredients: [
          "2 slices artisanal sourdough bread",
          "2 large pasture-raised eggs",
          "1/2 ripe Haas avocado",
          "1 cup baby spinach",
          "1 tbsp chia seeds",
          "Pinch of sea salt and red chili flakes"
        ],
        instructions: [
          "Toast sourdough slices until golden and crisp.",
          "Mash avocado with lime juice, salt, and pepper; spread over toast.",
          "Poach eggs in simmering water with a drop of vinegar for 3-4 minutes.",
          "Top toast with sautéed baby spinach and poached eggs, then sprinkle chia seeds."
        ],
        imageEmoji: "🥑"
      },
      {
        id: "m1_2",
        type: "Lunch",
        name: "Grilled Citrus Chicken & Quinoa Mediterranean Bowl",
        calories: 580,
        protein: 48,
        carbs: 52,
        fats: 16,
        fiber: 7,
        prepTime: "20 min",
        category: "Proteins / Grains / Produce",
        allergenTags: [],
        vegetarianSafe: false,
        veganSafe: false,
        ingredients: [
          "180g lean chicken breast (or extra-firm tofu)",
          "3/4 cup cooked organic quinoa",
          "1/2 cup English cucumber (diced)",
          "1/2 cup cherry tomatoes (halved)",
          "30g Kalamata olives",
          "1 tbsp extra virgin olive oil & lemon vinaigrette"
        ],
        instructions: [
          "Season chicken breast with oregano, garlic powder, salt, and lemon juice.",
          "Grill on medium-high heat for 6-7 minutes each side until internal temp reaches 74°C.",
          "Assemble quinoa bowl with diced cucumber, tomatoes, olives, and sliced chicken.",
          "Drizzle with cold-pressed olive oil dressing."
        ],
        imageEmoji: "🥗"
      },
      {
        id: "m1_3",
        type: "Snack",
        name: "Greek Yogurt Berry Parfait with Almond Butter",
        calories: 260,
        protein: 22,
        carbs: 24,
        fats: 8,
        fiber: 3,
        prepTime: "5 min",
        category: "Dairy / Produce / Pantry",
        allergenTags: ["dairy", "nuts"],
        vegetarianSafe: true,
        veganSafe: false,
        ingredients: [
          "1 cup 0% Greek Yogurt (or coconut protein yogurt)",
          "1/2 cup fresh wild blueberries",
          "1 tbsp natural almond butter",
          "1 tsp organic honey or stevia"
        ],
        instructions: [
          "Layer Greek yogurt and fresh blueberries in a glass bowl.",
          "Drizzle almond butter and raw honey over top."
        ],
        imageEmoji: "🫐"
      },
      {
        id: "m1_4",
        type: "Dinner",
        name: "Herb-Crusted Wild Salmon with Roasted Asparagus & Sweet Potato",
        calories: 540,
        protein: 42,
        carbs: 40,
        fats: 20,
        fiber: 6,
        prepTime: "25 min",
        category: "Proteins / Produce",
        allergenTags: ["fish"],
        vegetarianSafe: false,
        veganSafe: false,
        ingredients: [
          "170g Wild Alaskan Salmon fillet",
          "150g sweet potato (cubed)",
          "1 bunch tender green asparagus",
          "1 tbsp rosemary and garlic olive oil marinade"
        ],
        instructions: [
          "Preheat oven to 200°C (400°F).",
          "Toss sweet potato cubes in olive oil and roast for 15 minutes.",
          "Add salmon fillet and asparagus to baking sheet; bake for additional 12 minutes.",
          "Serve fresh with lemon wedges."
        ],
        imageEmoji: "🐟"
      }
    ],
    Tue: [
      {
        id: "m2_1",
        type: "Breakfast",
        name: "Overnight Steel-Cut Oats with Whey, Chia & Strawberries",
        calories: 410,
        protein: 32,
        carbs: 48,
        fats: 9,
        fiber: 9,
        prepTime: "5 min + overnight",
        category: "Grains / Dairy / Produce",
        allergenTags: ["dairy", "gluten"],
        vegetarianSafe: true,
        veganSafe: false,
        ingredients: ["50g rolled oats", "1 scoop vanilla whey/plant protein", "1 tbsp chia seeds", "1/2 cup almond milk", "1/2 cup sliced strawberries"],
        instructions: ["Mix oats, protein, chia seeds, and almond milk. Chill overnight. Top with fresh strawberries."],
        imageEmoji: "🍓"
      },
      {
        id: "m2_2",
        type: "Lunch",
        name: "Turkey Breast & Hummus Whole Grain Wrap with Greens",
        calories: 520,
        protein: 44,
        carbs: 46,
        fats: 14,
        fiber: 8,
        prepTime: "10 min",
        category: "Proteins / Bakery / Produce",
        allergenTags: ["gluten", "sesame"],
        vegetarianSafe: false,
        veganSafe: false,
        ingredients: ["1 large whole-grain flatbread", "150g sliced roasted turkey", "2 tbsp roasted garlic hummus", "1 cup mixed greens", "1/4 red onion"],
        instructions: ["Spread hummus over wrap. Layer turkey, greens, and onions. Roll tightly and slice in half."],
        imageEmoji: "🌯"
      },
      {
        id: "m2_3",
        type: "Snack",
        name: "Apple Slices with Natural Peanut Butter & Walnuts",
        calories: 240,
        protein: 8,
        carbs: 26,
        fats: 12,
        fiber: 4,
        prepTime: "3 min",
        category: "Produce / Pantry",
        allergenTags: ["nuts", "peanuts"],
        vegetarianSafe: true,
        veganSafe: true,
        ingredients: ["1 crisp Honeycrisp apple", "1.5 tbsp natural peanut butter", "15g raw walnut halves"],
        instructions: ["Slice apple thinly and serve with peanut butter and crushed walnuts."],
        imageEmoji: "🍎"
      },
      {
        id: "m2_4",
        type: "Dinner",
        name: "Lean Grass-Fed Beef Stir-Fry with Broccoli & Jasmine Rice",
        calories: 590,
        protein: 46,
        carbs: 55,
        fats: 15,
        fiber: 6,
        prepTime: "20 min",
        category: "Proteins / Produce / Grains",
        allergenTags: ["soy"],
        vegetarianSafe: false,
        veganSafe: false,
        ingredients: ["160g lean beef strips", "1.5 cups broccoli florets", "1/2 bell pepper", "3/4 cup steamed jasmine rice", "1 tbsp low-sodium tamari soy sauce"],
        instructions: ["Stir-fry beef in hot wok with sesame oil for 3 minutes. Add broccoli and bell peppers. Toss with tamari and serve over jasmine rice."],
        imageEmoji: "🥩"
      }
    ],
    Wed: [
      {
        id: "m3_1",
        type: "Breakfast",
        name: "Spinach, Feta & Egg White Scramble with Rye Toast",
        calories: 390,
        protein: 30,
        carbs: 32,
        fats: 12,
        fiber: 5,
        prepTime: "10 min",
        category: "Dairy / Produce / Bakery",
        allergenTags: ["dairy", "eggs", "gluten"],
        vegetarianSafe: true,
        veganSafe: false,
        ingredients: ["4 egg whites + 1 whole egg", "1.5 cups baby spinach", "30g crumbled Greek feta", "1 slice dark rye bread"],
        instructions: ["Whisk eggs. Sauté spinach in olive oil spray, pour eggs, scramble lightly, fold in feta."],
        imageEmoji: "🍳"
      },
      {
        id: "m3_2",
        type: "Lunch",
        name: "Wild Tuna & White Bean Rainbow Salad",
        calories: 510,
        protein: 46,
        carbs: 42,
        fats: 13,
        fiber: 10,
        prepTime: "12 min",
        category: "Proteins / Pantry / Produce",
        allergenTags: ["fish"],
        vegetarianSafe: false,
        veganSafe: false,
        ingredients: ["1 can chunk light wild tuna in water", "1/2 cup cannellini beans", "Cherry tomatoes", "Arugula", "Balsamic glaze"],
        instructions: ["Drain tuna and rinse beans. Toss with arugula, halved cherry tomatoes, olive oil, and balsamic vinegar."],
        imageEmoji: "🥗"
      },
      {
        id: "m3_3",
        type: "Snack",
        name: "Protein Shake with Almond Milk & Banana",
        calories: 250,
        protein: 28,
        carbs: 26,
        fats: 3,
        fiber: 2,
        prepTime: "3 min",
        category: "Pantry / Produce",
        allergenTags: ["nuts"],
        vegetarianSafe: true,
        veganSafe: true,
        ingredients: ["1 scoop Isolate protein", "1 cup unsweetened almond milk", "1 medium ripe banana"],
        instructions: ["Blend with ice cubes until frothy and smooth."],
        imageEmoji: "🥤"
      },
      {
        id: "m3_4",
        type: "Dinner",
        name: "Spiced Chickpea & Paneer/Tofu Tikka with Cauli-Rice",
        calories: 550,
        protein: 36,
        carbs: 45,
        fats: 20,
        fiber: 11,
        prepTime: "25 min",
        category: "Dairy / Proteins / Produce",
        allergenTags: ["dairy", "soy"],
        vegetarianSafe: true,
        veganSafe: true, // when using tofu variant
        ingredients: ["150g cottage cheese/paneer or tofu", "1/2 cup spiced chickpeas", "1.5 cups riced cauliflower", "Indian garam masala & cumin"],
        instructions: ["Roast marinated paneer cubes and chickpeas in air fryer/oven. Sauté riced cauliflower with turmeric and cilantro."],
        imageEmoji: "🍛"
      }
    ],
    Thu: [
      {
        id: "m4_1",
        type: "Breakfast",
        name: "Banana Walnut Protein Pancakes",
        calories: 430,
        protein: 32,
        carbs: 45,
        fats: 11,
        fiber: 4,
        prepTime: "15 min",
        category: "Grains / Dairy / Produce",
        allergenTags: ["eggs", "gluten", "nuts"],
        vegetarianSafe: true,
        veganSafe: false,
        ingredients: ["1 mashed banana", "2 eggs", "1/2 scoop vanilla protein powder", "30g oat flour", "10g chopped walnuts"],
        instructions: ["Whisk batter together and cook on non-stick griddle 2 min per side. Top with walnuts."],
        imageEmoji: "🥞"
      },
      {
        id: "m4_2",
        type: "Lunch",
        name: "Mexican Grilled Chicken Burrito Bowl",
        calories: 570,
        protein: 48,
        carbs: 56,
        fats: 15,
        fiber: 12,
        prepTime: "15 min",
        category: "Proteins / Produce / Grains",
        allergenTags: [],
        vegetarianSafe: false,
        veganSafe: false,
        ingredients: ["170g spiced chicken breast", "1/2 cup black beans", "1/2 cup brown rice", "Fresh pico de gallo", "2 tbsp guacamole"],
        instructions: ["Layer warm brown rice and seasoned black beans. Top with sliced chicken, fresh pico de gallo, and guacamole."],
        imageEmoji: "🥑"
      },
      {
        id: "m4_3",
        type: "Snack",
        name: "Edamame Beans with Sea Salt & Sesame",
        calories: 200,
        protein: 17,
        carbs: 15,
        fats: 7,
        fiber: 5,
        prepTime: "5 min",
        category: "Produce / Pantry",
        allergenTags: ["soy"],
        vegetarianSafe: true,
        veganSafe: true,
        ingredients: ["1.5 cups steamed edamame pods", "Flaky sea salt", "Toasted sesame oil drizzle"],
        instructions: ["Steam edamame for 4 minutes. Toss in sea salt and sesame oil."],
        imageEmoji: "🫛"
      },
      {
        id: "m4_4",
        type: "Dinner",
        name: "Baked Cod Loin with Lemon-Caper Sauce & Wild Rice",
        calories: 520,
        protein: 44,
        carbs: 42,
        fats: 14,
        fiber: 3,
        prepTime: "22 min",
        category: "Proteins / Grains / Produce",
        allergenTags: ["fish", "dairy"],
        vegetarianSafe: false,
        veganSafe: false,
        ingredients: ["180g Atlantic cod fillet", "1 tbsp butter & capers", "3/4 cup cooked wild rice", "Steamed French green beans"],
        instructions: ["Bake cod at 190°C for 15 min. Spoon warm lemon caper reduction on top. Serve with wild rice and beans."],
        imageEmoji: "🐟"
      }
    ],
    Fri: [
      {
        id: "m5_1",
        type: "Breakfast",
        name: "Smoked Salmon & Cottage Cheese Multigrain Toast",
        calories: 400,
        protein: 34,
        carbs: 34,
        fats: 12,
        fiber: 3,
        prepTime: "8 min",
        category: "Proteins / Dairy / Bakery",
        allergenTags: ["fish", "dairy", "gluten"],
        vegetarianSafe: false,
        veganSafe: false,
        ingredients: ["2 slices seeded bread", "1/2 cup low-fat cottage cheese", "80g smoked salmon", "Fresh dill & capers"],
        instructions: ["Spread cottage cheese over toasted bread. Layer smoked salmon, garnish with fresh dill and cracked pepper."],
        imageEmoji: "🥪"
      },
      {
        id: "m5_2",
        type: "Lunch",
        name: "Mediterranean Lentil & Feta Power Bowl",
        calories: 530,
        protein: 32,
        carbs: 60,
        fats: 16,
        fiber: 14,
        prepTime: "15 min",
        category: "Grains / Dairy / Produce",
        allergenTags: ["dairy", "sesame"],
        vegetarianSafe: true,
        veganSafe: false,
        ingredients: ["1 cup brown lentils (cooked)", "40g feta cheese", "Roasted red peppers", "Kalamata olives", "Tahini lemon dressing"],
        instructions: ["Toss warm lentils with roasted red peppers, diced olives, crumbled feta, and tahini dressing."],
        imageEmoji: "🍲"
      },
      {
        id: "m5_3",
        type: "Snack",
        name: "Cottage Cheese with Pineapple Chunks",
        calories: 210,
        protein: 20,
        carbs: 22,
        fats: 3,
        fiber: 1,
        prepTime: "3 min",
        category: "Dairy / Produce",
        allergenTags: ["dairy"],
        vegetarianSafe: true,
        veganSafe: false,
        ingredients: ["3/4 cup 2% cottage cheese", "1/2 cup fresh diced pineapple"],
        instructions: ["Combine cottage cheese with sweet chilled pineapple chunks."],
        imageEmoji: "🍍"
      },
      {
        id: "m5_4",
        type: "Dinner",
        name: "Lean Turkey Bolognese with Protein Pasta & Zucchini",
        calories: 580,
        protein: 48,
        carbs: 52,
        fats: 15,
        fiber: 7,
        prepTime: "25 min",
        category: "Proteins / Grains / Produce",
        allergenTags: ["gluten"],
        vegetarianSafe: false,
        veganSafe: false,
        ingredients: ["160g ground lean turkey", "70g chickpea/protein pasta", "1 cup marinara sauce", "1 cup sautéed spiralized zucchini"],
        instructions: ["Brown ground turkey with Italian herbs. Simmer with marinara sauce. Toss with cooked protein pasta and zucchini ribbons."],
        imageEmoji: "🍝"
      }
    ],
    Sat: [
      {
        id: "m6_1",
        type: "Breakfast",
        name: "NutriAI Superfood Acai & Whey Protein Bowl",
        calories: 440,
        protein: 30,
        carbs: 50,
        fats: 12,
        fiber: 8,
        prepTime: "10 min",
        category: "Produce / Dairy / Pantry",
        allergenTags: ["dairy", "nuts"],
        vegetarianSafe: true,
        veganSafe: false,
        ingredients: ["1 unsweetened acai packet", "1 scoop berry whey protein", "1/2 frozen banana", "Toppings: Chia seeds, cacao nibs, blueberries"],
        instructions: ["Blend acai, whey protein, and frozen banana until thick. Top with superfoods."],
        imageEmoji: "🥣"
      },
      {
        id: "m6_2",
        type: "Lunch",
        name: "Grilled Steak Cobb Salad with Herb Dressing",
        calories: 590,
        protein: 46,
        carbs: 20,
        fats: 32,
        fiber: 4,
        prepTime: "20 min",
        category: "Proteins / Produce / Dairy",
        allergenTags: ["dairy", "eggs"],
        vegetarianSafe: false,
        veganSafe: false,
        ingredients: ["150g grilled flank steak", "1 hard-boiled egg", "1/3 avocado", "Romaine lettuce", "Cherry tomatoes", "Light blue cheese vinaigrette"],
        instructions: ["Chop romaine lettuce. Arrange sliced steak, egg halves, avocado slices, and tomatoes. Drizzle dressing."],
        imageEmoji: "🥗"
      },
      {
        id: "m6_3",
        type: "Snack",
        name: "Roasted Pumpkin Seeds & Dark Chocolate (85%)",
        calories: 220,
        protein: 8,
        carbs: 14,
        fats: 16,
        fiber: 3,
        prepTime: "2 min",
        category: "Pantry",
        allergenTags: [],
        vegetarianSafe: true,
        veganSafe: true,
        ingredients: ["25g unsalted pumpkin seeds (pepitas)", "2 squares 85% single-origin dark chocolate"],
        instructions: ["Enjoy as an antioxidant-rich afternoon snack."],
        imageEmoji: "🍫"
      },
      {
        id: "m6_4",
        type: "Dinner",
        name: "Crispy Sesame Tofu / Chicken with Sautéed Bok Choy & Rice",
        calories: 540,
        protein: 38,
        carbs: 54,
        fats: 16,
        fiber: 5,
        prepTime: "20 min",
        category: "Proteins / Produce / Grains",
        allergenTags: ["soy"],
        vegetarianSafe: true, // using tofu variant
        veganSafe: true,      // using tofu variant
        ingredients: ["180g pressed firm tofu or chicken strips", "2 heads baby bok choy", "3/4 cup brown rice", "Ginger-sesame glaze"],
        instructions: ["Pan-sear tofu/chicken until crisp on all sides. Sauté bok choy with ginger and garlic. Serve with rice and sesame drizzle."],
        imageEmoji: "🥢"
      }
    ],
    Sun: [
      {
        id: "m7_1",
        type: "Breakfast",
        name: "Sunday Shakshuka (Eggs Poached in Spiced Tomato Pepper Sauce)",
        calories: 420,
        protein: 26,
        carbs: 35,
        fats: 18,
        fiber: 7,
        prepTime: "20 min",
        category: "Proteins / Produce / Bakery",
        allergenTags: ["eggs", "gluten"],
        vegetarianSafe: true,
        veganSafe: false,
        ingredients: ["3 organic eggs", "1 can San Marzano crushed tomatoes", "1 bell pepper", "1 tbsp cumin & smoked paprika", "1 slice crusty sourdough"],
        instructions: ["Simmer bell pepper and spices in crushed tomatoes for 10 min. Make 3 wells, crack eggs into sauce, cover and cook until whites set. Serve with warm sourdough."],
        imageEmoji: "🍳"
      },
      {
        id: "m7_2",
        type: "Lunch",
        name: "Lemon Herb Grilled Salmon with Quinoa & Beetroot Salad",
        calories: 560,
        protein: 44,
        carbs: 42,
        fats: 20,
        fiber: 6,
        prepTime: "20 min",
        category: "Proteins / Grains / Produce",
        allergenTags: ["fish", "dairy"],
        vegetarianSafe: false,
        veganSafe: false,
        ingredients: ["170g wild salmon", "3/4 cup cooked quinoa", "1/2 cup roasted pickled beetroot cubes", "Arugula & goat cheese crumbles"],
        instructions: ["Pan-sear salmon in cast-iron skillet. Assemble quinoa, arugula, beets, and goat cheese."],
        imageEmoji: "🥗"
      },
      {
        id: "m7_3",
        type: "Snack",
        name: "Pistachios & Clementine Mandarins",
        calories: 210,
        protein: 6,
        carbs: 22,
        fats: 11,
        fiber: 4,
        prepTime: "2 min",
        category: "Produce / Pantry",
        allergenTags: ["nuts"],
        vegetarianSafe: true,
        veganSafe: true,
        ingredients: ["30g dry-roasted in-shell pistachios", "2 fresh clementine mandarins"],
        instructions: ["Quick energizing afternoon fruit & nut pair."],
        imageEmoji: "🍊"
      },
      {
        id: "m7_4",
        type: "Dinner",
        name: "Hearty Lentil Shepherd's Pie with Sweet Potato Mash",
        calories: 530,
        protein: 34,
        carbs: 62,
        fats: 12,
        fiber: 16,
        prepTime: "30 min",
        category: "Grains / Produce / Pantry",
        allergenTags: [],
        vegetarianSafe: true,
        veganSafe: true,
        ingredients: ["1.5 cups French green lentils & minced vegetables", "1 cup mashed sweet potato", "Rosemary & thyme seasoning"],
        instructions: ["Simmer lentils with carrots, celery, onions, and herbs. Top with creamy sweet potato mash and bake at 200°C for 15 min."],
        imageEmoji: "🥧"
      }
    ]
  },

  // Expanded Alternative Meal Pools for Dietary, Allergy & Cuisine Adaptations
  alternativeMealPool: [
    // --- Asian Cuisine Pool ---
    {
      id: "alt_asian_b1",
      type: "Breakfast",
      name: "Japanese Tamagoyaki Rolled Eggs & Steamed Edamame",
      calories: 360,
      protein: 26,
      carbs: 22,
      fats: 16,
      fiber: 4,
      prepTime: "10 min",
      cuisine: "asian",
      category: "Proteins / Produce",
      allergenTags: ["eggs", "soy"],
      vegetarianSafe: true,
      veganSafe: false,
      pescatarianSafe: true,
      ingredients: ["3 large pasture-raised eggs", "1/2 cup shelled edamame", "1 tbsp gluten-free tamari", "1 tsp mirin", "1 tsp sesame oil"],
      instructions: ["Beat eggs with tamari and mirin. Layer and roll in non-stick pan. Serve with warm steamed edamame."],
      imageEmoji: "🍳"
    },
    {
      id: "alt_asian_b2",
      type: "Breakfast",
      name: "Silken Tofu & Wakame Miso Bowl with Steamed Rice",
      calories: 340,
      protein: 22,
      carbs: 42,
      fats: 8,
      fiber: 4,
      prepTime: "8 min",
      cuisine: "asian",
      category: "Plant Proteins / Grains",
      allergenTags: ["soy"],
      vegetarianSafe: true,
      veganSafe: true,
      pescatarianSafe: true,
      ingredients: ["150g soft silken tofu", "1 cup warm white miso broth (gluten-free)", "1/2 cup steamed jasmine rice", "1 tbsp sliced scallions", "1 sheet crushed nori"],
      instructions: ["Warm gluten-free miso broth. Add cubed silken tofu, scallions, and nori flakes. Serve alongside steamed rice."],
      imageEmoji: "🥣"
    },
    {
      id: "alt_asian_l1",
      type: "Lunch",
      name: "Sesame-Seared Ahi Tuna & Avocado Brown Rice Bowl",
      calories: 480,
      protein: 38,
      carbs: 44,
      fats: 15,
      fiber: 6,
      prepTime: "15 min",
      cuisine: "asian",
      category: "Proteins / Grains / Produce",
      allergenTags: ["fish", "sesame"],
      vegetarianSafe: false,
      veganSafe: false,
      pescatarianSafe: true,
      ingredients: ["150g sashimi-grade yellowfin tuna", "1/2 cup cooked brown rice", "1/2 ripe avocado", "1/2 cup steamed edamame", "1 tbsp sesame-ginger vinaigrette"],
      instructions: ["Crust tuna with sesame seeds and sear 1 min per side in hot skillet. Slice and serve over brown rice with avocado and edamame."],
      imageEmoji: "🍱"
    },
    {
      id: "alt_asian_l2",
      type: "Lunch",
      name: "Thai Ginger Steamed Halibut with Bok Choy & Jasmine Rice",
      calories: 460,
      protein: 40,
      carbs: 46,
      fats: 10,
      fiber: 4,
      prepTime: "18 min",
      cuisine: "asian",
      category: "Proteins / Produce / Grains",
      allergenTags: ["fish"],
      vegetarianSafe: false,
      veganSafe: false,
      pescatarianSafe: true,
      ingredients: ["160g wild halibut or cod fillet", "2 heads baby bok choy", "1/2 cup steamed jasmine rice", "1 tbsp julienned fresh ginger", "1 tbsp gluten-free tamari"],
      instructions: ["Steam fish fillet with ginger and scallions for 10 min. Steam bok choy alongside. Drizzle with tamari and serve with warm jasmine rice."],
      imageEmoji: "🐟"
    },
    {
      id: "alt_asian_l3",
      type: "Lunch",
      name: "Crispy Pan-Seared Tofu & Broccoli with Garlic Tamari Sauce",
      calories: 420,
      protein: 26,
      carbs: 48,
      fats: 14,
      fiber: 7,
      prepTime: "15 min",
      cuisine: "asian",
      category: "Plant Proteins / Produce",
      allergenTags: ["soy"],
      vegetarianSafe: true,
      veganSafe: true,
      pescatarianSafe: true,
      ingredients: ["180g extra-firm organic tofu (cubed)", "1.5 cups fresh broccoli florets", "1/2 cup brown rice", "1 tbsp minced garlic & ginger", "1 tbsp gluten-free tamari"],
      instructions: ["Pan-sear pressed tofu cubes until crispy. Toss with steamed broccoli, garlic, and tamari glaze. Serve over brown rice."],
      imageEmoji: "🥢"
    },
    {
      id: "alt_asian_d1",
      type: "Dinner",
      name: "Miso-Glazed Wild Salmon with Sautéed Baby Greens & Rice",
      calories: 510,
      protein: 42,
      carbs: 38,
      fats: 18,
      fiber: 5,
      prepTime: "20 min",
      cuisine: "asian",
      category: "Proteins / Produce / Grains",
      allergenTags: ["fish", "soy"],
      vegetarianSafe: false,
      veganSafe: false,
      pescatarianSafe: true,
      ingredients: ["160g wild Alaskan salmon", "1 tbsp white miso paste (gluten-free)", "1 tsp honey", "1.5 cups baby spinach & bok choy", "1/2 cup jasmine rice"],
      instructions: ["Brush salmon with miso glaze and broil for 8-10 min. Sauté greens in a drop of sesame oil. Serve hot over jasmine rice."],
      imageEmoji: "🍣"
    },
    {
      id: "alt_asian_d2",
      type: "Dinner",
      name: "Asian Steamed Cod Fillet with Scallions, Ginger & Brown Rice",
      calories: 440,
      protein: 38,
      carbs: 42,
      fats: 9,
      fiber: 4,
      prepTime: "18 min",
      cuisine: "asian",
      category: "Proteins / Produce / Grains",
      allergenTags: ["fish"],
      vegetarianSafe: false,
      veganSafe: false,
      pescatarianSafe: true,
      ingredients: ["170g Atlantic cod fillet", "2 spring onions (shredded)", "1 tbsp sliced ginger", "1/2 cup steamed brown rice", "1 tbsp cold-pressed sesame oil"],
      instructions: ["Place cod in steamer basket topped with ginger and scallions. Steam for 9 min. Pour hot sesame oil and tamari over top. Serve with brown rice."],
      imageEmoji: "🍲"
    },
    {
      id: "alt_asian_d3",
      type: "Dinner",
      name: "Coconut Curry Lentils with Roasted Vegetables & Jasmine Rice",
      calories: 470,
      protein: 24,
      carbs: 62,
      fats: 12,
      fiber: 14,
      prepTime: "22 min",
      cuisine: "asian",
      category: "Grains / Legumes / Produce",
      allergenTags: [],
      vegetarianSafe: true,
      veganSafe: true,
      pescatarianSafe: true,
      ingredients: ["1 cup cooked brown lentils", "1/3 cup light coconut milk", "1/2 cup zucchini & bell peppers", "1 tsp yellow curry paste", "1/2 cup jasmine rice"],
      instructions: ["Simmer lentils and veggies in coconut curry broth for 12 min. Serve warm over jasmine rice."],
      imageEmoji: "🍛"
    },
    // --- Gluten-Free / Mediterranean / General Pool ---
    {
      id: "alt_gf_b1",
      type: "Breakfast",
      name: "Gluten-Free Chia Berry Coconut Protein Parfait",
      calories: 360,
      protein: 24,
      carbs: 32,
      fats: 14,
      fiber: 9,
      prepTime: "5 min",
      cuisine: "mediterranean",
      category: "Produce / Dairy / Pantry",
      allergenTags: [],
      vegetarianSafe: true,
      veganSafe: true,
      pescatarianSafe: true,
      ingredients: ["1 cup unsweetened coconut yogurt", "1 scoop plant protein", "2 tbsp chia seeds", "1/2 cup wild blueberries"],
      instructions: ["Layer yogurt, plant protein, chia seeds, and wild blueberries in a glass bowl."],
      imageEmoji: "🫐"
    },
    {
      id: "alt_gf_l1",
      type: "Lunch",
      name: "Mediterranean Greek Salad with Grilled Halibut & Olives",
      calories: 460,
      protein: 38,
      carbs: 18,
      fats: 24,
      fiber: 6,
      prepTime: "15 min",
      cuisine: "mediterranean",
      category: "Proteins / Produce",
      allergenTags: ["fish"],
      vegetarianSafe: false,
      veganSafe: false,
      pescatarianSafe: true,
      ingredients: ["160g grilled halibut", "1 cup English cucumber", "1 cup cherry tomatoes", "10 Kalamata olives", "1 tbsp extra virgin olive oil"],
      instructions: ["Toss cucumber, tomatoes, and olives in olive oil and oregano. Top with grilled halibut."],
      imageEmoji: "🥗"
    },

    // --- Authentic Indian / South Asian Cuisine Pool ---
    // Indian Breakfasts
    {
      id: "alt_ind_b1",
      type: "Breakfast",
      name: "Spiced Paneer Bhurji with Sautéed Baby Spinach",
      calories: 380,
      protein: 28,
      carbs: 16,
      fats: 22,
      fiber: 5,
      prepTime: "12 min",
      cuisine: "indian",
      category: "Dairy / Produce / Spices",
      allergenTags: ["dairy"],
      vegetarianSafe: true,
      veganSafe: false,
      pescatarianSafe: true,
      ingredients: ["150g crumbled fresh paneer", "1.5 cups baby spinach", "1/2 diced red onion", "1 green chili & turmeric", "1 tsp cumin seeds & ghee"],
      instructions: ["Heat ghee, splutter cumin seeds, sauté onions, chilies, and turmeric. Add crumbled paneer and fresh spinach. Scramble for 4-5 min."],
      imageEmoji: "🍳"
    },
    {
      id: "alt_ind_b2",
      type: "Breakfast",
      name: "Indian Masala Egg Omelette with Coriander & Green Chilies",
      calories: 350,
      protein: 24,
      carbs: 10,
      fats: 22,
      fiber: 3,
      prepTime: "10 min",
      cuisine: "indian",
      category: "Proteins / Produce",
      allergenTags: ["eggs"],
      vegetarianSafe: true,
      veganSafe: false,
      pescatarianSafe: true,
      ingredients: ["3 large pasture-raised eggs", "1/2 finely chopped red onion", "1 Roma tomato (diced)", "Fresh cilantro / coriander", "Pinch of garam masala & rock salt"],
      instructions: ["Whisk eggs with onions, tomatoes, coriander, turmeric, and rock salt. Cook in a non-stick pan with olive oil or ghee until golden on both sides."],
      imageEmoji: "🥚"
    },
    {
      id: "alt_ind_b3",
      type: "Breakfast",
      name: "Moong Dal Cheela (Yellow Lentil Crepes) with Mint Chutney",
      calories: 340,
      protein: 22,
      carbs: 44,
      fats: 8,
      fiber: 9,
      prepTime: "15 min",
      cuisine: "indian",
      category: "Legumes / Produce",
      allergenTags: [],
      vegetarianSafe: true,
      veganSafe: true,
      pescatarianSafe: true,
      ingredients: ["1/2 cup soaked yellow moong dal batter", "1 tbsp grated ginger & green chili", "Fresh mint & cilantro chutney", "1 tsp cold-pressed oil"],
      instructions: ["Spread moong dal batter onto a hot tawa like a thin crepe. Cook until crispy on both sides. Serve with fresh mint-coriander chutney."],
      imageEmoji: "🥞"
    },
    {
      id: "alt_ind_b4",
      type: "Breakfast",
      name: "Spiced Poha with Crunchy Peanuts, Curry Leaves & Lime",
      calories: 320,
      protein: 10,
      carbs: 52,
      fats: 9,
      fiber: 5,
      prepTime: "12 min",
      cuisine: "indian",
      category: "Grains / Produce / Nuts",
      allergenTags: ["peanuts", "nuts"],
      vegetarianSafe: true,
      veganSafe: true,
      pescatarianSafe: true,
      ingredients: ["1 cup flattened rice (poha)", "2 tbsp roasted peanuts", "Fresh curry leaves & mustard seeds", "1/2 cup green peas", "Juice of 1/2 fresh lime"],
      instructions: ["Rinse poha. Temper mustard seeds and curry leaves in 1 tsp oil, add peanuts and green peas. Fold in poha and turmeric. Finish with fresh lime juice."],
      imageEmoji: "🥣"
    },
    {
      id: "alt_ind_b5",
      type: "Breakfast",
      name: "Steamed Idli with Protein Sambar & Coconut Chutney",
      calories: 330,
      protein: 14,
      carbs: 56,
      fats: 5,
      fiber: 6,
      prepTime: "15 min",
      cuisine: "indian",
      category: "Grains / Legumes / Produce",
      allergenTags: [],
      vegetarianSafe: true,
      veganSafe: true,
      pescatarianSafe: true,
      ingredients: ["3 steamed rice & urad dal idlis", "1 cup hot vegetable toor dal sambar", "1 tbsp fresh coconut chutney"],
      instructions: ["Steam fermented idlis until soft and fluffy. Serve with hot drumstick-vegetable sambar and coconut chutney."],
      imageEmoji: "⚪"
    },

    // Indian Lunches
    {
      id: "alt_ind_l1",
      type: "Lunch",
      name: "Goan Coconut Fish Curry with Steamed Brown Basmati Rice",
      calories: 480,
      protein: 42,
      carbs: 45,
      fats: 14,
      fiber: 5,
      prepTime: "22 min",
      cuisine: "indian",
      category: "Proteins / Grains / Spices",
      allergenTags: ["fish"],
      vegetarianSafe: false,
      veganSafe: false,
      pescatarianSafe: true,
      ingredients: ["170g wild sea bass or pomfret fillet", "1/3 cup light coconut milk", "1/2 cup steamed brown basmati rice", "1 tbsp Kashmiri chili & tamarind paste", "Fresh coriander"],
      instructions: ["Simmer fish in aromatic Goan coconut-tamarind gravy for 8-10 min. Serve hot over steamed brown basmati rice."],
      imageEmoji: "🐟"
    },
    {
      id: "alt_ind_l2",
      type: "Lunch",
      name: "Authentic Punjabi Chana Masala with Jeera Brown Rice",
      calories: 450,
      protein: 20,
      carbs: 68,
      fats: 10,
      fiber: 14,
      prepTime: "20 min",
      cuisine: "indian",
      category: "Legumes / Grains / Produce",
      allergenTags: [],
      vegetarianSafe: true,
      veganSafe: true,
      pescatarianSafe: true,
      ingredients: ["1.5 cups boiled chickpeas (chana)", "1 cup tomato-onion spiced masala gravy", "1/2 cup cumin (jeera) brown rice", "Fresh ginger juliennes & lime"],
      instructions: ["Simmer chickpeas in spiced tomato-onion masala with roasted cumin and coriander. Serve with fragrant jeera brown rice."],
      imageEmoji: "🍛"
    },
    {
      id: "alt_ind_l3",
      type: "Lunch",
      name: "Tawa-Seared Masala Fish with Fresh Cucumber Mint Raita",
      calories: 420,
      protein: 44,
      carbs: 16,
      fats: 18,
      fiber: 4,
      prepTime: "15 min",
      cuisine: "indian",
      category: "Proteins / Dairy / Produce",
      allergenTags: ["fish", "dairy"],
      vegetarianSafe: false,
      veganSafe: false,
      pescatarianSafe: true,
      ingredients: ["180g kingfish or pomfret fillet", "1 tbsp carom seeds (ajwain), red chili & turmeric marinade", "1/2 cup Greek yogurt cucumber raita", "Lemon wedges"],
      instructions: ["Rub fish with ajwain, turmeric, chili, and lemon juice. Pan-sear on a hot tawa for 4-5 min per side until crisp. Serve with cool cucumber raita."],
      imageEmoji: "🐠"
    },
    {
      id: "alt_ind_l4",
      type: "Lunch",
      name: "Palak Paneer (Pureed Spinach & Cottage Cheese) with Quinoa",
      calories: 460,
      protein: 26,
      carbs: 38,
      fats: 24,
      fiber: 7,
      prepTime: "20 min",
      cuisine: "indian",
      category: "Dairy / Produce / Grains",
      allergenTags: ["dairy"],
      vegetarianSafe: true,
      veganSafe: false,
      pescatarianSafe: true,
      ingredients: ["150g cubed fresh paneer", "2 cups blanched pureed spinach", "1/2 cup cooked organic quinoa", "1 tsp garlic, ginger & garam masala"],
      instructions: ["Simmer pureed spinach with sautéed garlic, ginger, and spices. Fold in lightly pan-seared paneer cubes. Serve with warm quinoa."],
      imageEmoji: "🥬"
    },
    {
      id: "alt_ind_l5",
      type: "Lunch",
      name: "Tandoori Spiced Tofu Tikka Bowl with Mint Chutney & Brown Rice",
      calories: 430,
      protein: 28,
      carbs: 48,
      fats: 14,
      fiber: 8,
      prepTime: "20 min",
      cuisine: "indian",
      category: "Plant Proteins / Grains / Produce",
      allergenTags: ["soy"],
      vegetarianSafe: true,
      veganSafe: true,
      pescatarianSafe: true,
      ingredients: ["180g organic firm tofu cubes", "1 bell pepper & red onion chunks", "1 tbsp tandoori tikka masala", "1/2 cup steamed brown rice", "Fresh mint chutney"],
      instructions: ["Marinate tofu and bell peppers in tandoori spices and lemon. Grill or bake at 200°C for 15 min. Serve over brown rice with mint chutney."],
      imageEmoji: "🍢"
    },

    // Indian Snacks
    {
      id: "alt_ind_s1",
      type: "Snack",
      name: "Roasted Turmeric & Black Pepper Phool Makhana (Foxnuts)",
      calories: 180,
      protein: 6,
      carbs: 32,
      fats: 3,
      fiber: 4,
      prepTime: "5 min",
      cuisine: "indian",
      category: "Pantry / Spices",
      allergenTags: [],
      vegetarianSafe: true,
      veganSafe: true,
      pescatarianSafe: true,
      ingredients: ["35g puffed lotus seeds (phool makhana)", "1/2 tsp turmeric powder", "1/4 tsp crushed black pepper & rock salt", "1 tsp cold-pressed olive oil or ghee"],
      instructions: ["Dry roast makhana in a pan with ghee, turmeric, black pepper, and pink Himalayan salt until crispy."],
      imageEmoji: "🍿"
    },
    {
      id: "alt_ind_s2",
      type: "Snack",
      name: "Sprouted Moong & Pomegranate Chaat with Tangy Lemon",
      calories: 190,
      protein: 12,
      carbs: 30,
      fats: 2,
      fiber: 8,
      prepTime: "5 min",
      cuisine: "indian",
      category: "Produce / Legumes",
      allergenTags: [],
      vegetarianSafe: true,
      veganSafe: true,
      pescatarianSafe: true,
      ingredients: ["1 cup sprouted whole green moong", "2 tbsp pomegranate arils", "1/2 cucumber (diced)", "1 tsp chaat masala & fresh lime juice"],
      instructions: ["Toss sprouted moong beans with cucumber, pomegranate seeds, chaat masala, and a generous squeeze of fresh lime juice."],
      imageEmoji: "🥗"
    },
    {
      id: "alt_ind_s3",
      type: "Snack",
      name: "Cucumber & Mint Dahi Raita with Roasted Cumin",
      calories: 160,
      protein: 14,
      carbs: 10,
      fats: 5,
      fiber: 2,
      prepTime: "3 min",
      cuisine: "indian",
      category: "Dairy / Produce",
      allergenTags: ["dairy"],
      vegetarianSafe: true,
      veganSafe: false,
      pescatarianSafe: true,
      ingredients: ["1 cup Greek yogurt / fresh dahi", "1/2 grated English cucumber", "1/2 tsp roasted cumin powder", "Fresh mint leaves & rock salt"],
      instructions: ["Whisk dahi with grated cucumber, roasted cumin powder, rock salt, and chopped mint leaves. Serve chilled."],
      imageEmoji: "🥣"
    },
    {
      id: "alt_ind_s4",
      type: "Snack",
      name: "Masala Boiled Eggs with Chaat Spices & Lime",
      calories: 150,
      protein: 13,
      carbs: 2,
      fats: 10,
      fiber: 0.5,
      prepTime: "5 min",
      cuisine: "indian",
      category: "Proteins / Spices",
      allergenTags: ["eggs"],
      vegetarianSafe: true,
      veganSafe: false,
      pescatarianSafe: true,
      ingredients: ["2 hard-boiled eggs (sliced in half)", "1/2 tsp chaat masala & roasted cumin", "Pinch of Kashmiri chili powder & lemon juice"],
      instructions: ["Halve boiled eggs, sprinkle with chaat masala, roasted cumin, and red chili powder, and finish with fresh lemon juice."],
      imageEmoji: "🥚"
    },

    // Indian Dinners
    {
      id: "alt_ind_d1",
      type: "Dinner",
      name: "Kerala Coconut Fish Moilee with Steamed Brown Rice",
      calories: 490,
      protein: 40,
      carbs: 42,
      fats: 18,
      fiber: 4,
      prepTime: "22 min",
      cuisine: "indian",
      category: "Proteins / Grains / Spices",
      allergenTags: ["fish"],
      vegetarianSafe: false,
      veganSafe: false,
      pescatarianSafe: true,
      ingredients: ["170g white fish fillet (halibut or kingfish)", "1/2 cup coconut milk", "Fresh curry leaves, green chilies, ginger & turmeric", "1/2 cup steamed brown rice"],
      instructions: ["Gently poach fish in a fragrant coconut milk broth tempered with curry leaves, ginger, and green chilies. Serve with brown rice."],
      imageEmoji: "🍲"
    },
    {
      id: "alt_ind_d2",
      type: "Dinner",
      name: "Homestyle Yellow Dal Tadka with Steamed Basmati Rice & Greens",
      calories: 440,
      protein: 22,
      carbs: 68,
      fats: 8,
      fiber: 11,
      prepTime: "20 min",
      cuisine: "indian",
      category: "Legumes / Grains / Produce",
      allergenTags: [],
      vegetarianSafe: true,
      veganSafe: true,
      pescatarianSafe: true,
      ingredients: ["1.5 cups cooked yellow toor & moong dal", "1 tsp cumin, garlic & dried red chili tadka", "1/2 cup steamed basmati rice", "1 cup steamed green beans"],
      instructions: ["Cook yellow dal until creamy. Pour hot garlic-cumin ghee tadka over top. Serve with basmati rice and steamed green beans."],
      imageEmoji: "🍛"
    },
    {
      id: "alt_ind_d3",
      type: "Dinner",
      name: "Smoked Baingan Bharta (Roasted Eggplant) with Paneer & Jeera Rice",
      calories: 430,
      protein: 24,
      carbs: 34,
      fats: 22,
      fiber: 9,
      prepTime: "25 min",
      cuisine: "indian",
      category: "Produce / Dairy / Grains",
      allergenTags: ["dairy"],
      vegetarianSafe: true,
      veganSafe: false,
      pescatarianSafe: true,
      ingredients: ["1 large roasted smoked eggplant", "100g fresh paneer cubes", "1/2 cup jeera brown rice", "Sautéed onions, tomatoes & garam masala"],
      instructions: ["Char eggplant over flame, peel and mash. Sauté with onions, tomatoes, and spices. Stir in paneer cubes. Serve with jeera brown rice."],
      imageEmoji: "🍆"
    },
    {
      id: "alt_ind_d4",
      type: "Dinner",
      name: "Comforting Moong Dal & Quinoa Khichdi with Fresh Curd",
      calories: 420,
      protein: 20,
      carbs: 62,
      fats: 10,
      fiber: 8,
      prepTime: "20 min",
      cuisine: "indian",
      category: "Legumes / Grains / Dairy",
      allergenTags: ["dairy"],
      vegetarianSafe: true,
      veganSafe: false,
      pescatarianSafe: true,
      ingredients: ["1/2 cup yellow moong dal & quinoa", "1 tsp cumin seeds & turmeric", "1 tsp A2 cow ghee", "1/2 cup fresh homemade curd / dahi"],
      instructions: ["Pressure cook yellow moong dal and quinoa with turmeric, salt, and cumin ghee temper. Serve hot with a side of cool dahi."],
      imageEmoji: "🍲"
    },
    {
      id: "alt_ind_d5",
      type: "Dinner",
      name: "Bengali Mustard Fish Curry (Machher Jhol) with Steamed Rice",
      calories: 460,
      protein: 38,
      carbs: 44,
      fats: 12,
      fiber: 4,
      prepTime: "20 min",
      cuisine: "indian",
      category: "Proteins / Grains / Spices",
      allergenTags: ["fish", "mustard"],
      vegetarianSafe: false,
      veganSafe: false,
      pescatarianSafe: true,
      ingredients: ["170g Rohu or Salmon fillet", "1 tbsp ground yellow mustard paste & turmeric", "1/2 cup steamed jasmine rice", "1 green chili & nigella seeds (kalonji)"],
      instructions: ["Lightly fry fish with turmeric and salt. Simmer in a light mustard-kalonji broth with slit green chilies. Serve with steamed rice."],
      imageEmoji: "🐟"
    }
  ],

  // Food Database for Instant Logging Search (expanded with Indian staples & fiber)
  foodDatabase: [
    { name: "Whey Protein Isolate (1 scoop, 30g)", cals: 120, p: 25, c: 2, f: 1, fiber: 0, category: "Supplements" },
    { name: "Egg (Large, Whole, 1 pc)", cals: 72, p: 6, c: 0.4, f: 5, fiber: 0, category: "Dairy & Eggs" },
    { name: "Egg Whites (100g / ~3 eggs)", cals: 52, p: 11, c: 0.7, f: 0.2, fiber: 0, category: "Dairy & Eggs" },
    { name: "Paneer / Cottage Cheese (Fresh, 100g)", cals: 265, p: 18, c: 4, f: 20, fiber: 0, category: "Dairy & Eggs" },
    { name: "Moong Dal (Cooked, 1 cup / 200g)", cals: 212, p: 14, c: 38, f: 1, fiber: 8, category: "Legumes" },
    { name: "Chana Masala / Chickpea Curry (1 cup / 200g)", cals: 240, p: 12, c: 35, f: 6, fiber: 9, category: "Legumes" },
    { name: "Roti / Chapati (Whole Wheat, 1 pc / 40g)", cals: 104, p: 3.5, c: 22, f: 0.5, fiber: 3, category: "Bakery" },
    { name: "Steamed Idli (2 pcs / 80g)", cals: 130, p: 4, c: 28, f: 0.4, fiber: 2, category: "Grains & Starches" },
    { name: "Sambar (Vegetable Lentil Soup, 1 cup / 200ml)", cals: 110, p: 5, c: 18, f: 2.5, fiber: 4, category: "Legumes" },
    { name: "Roasted Makhana / Foxnuts (30g)", cals: 106, p: 3, c: 20, f: 0.3, fiber: 2, category: "Snacks" },
    { name: "Sprouted Moong Salad (1 cup / 150g)", cals: 120, p: 8, c: 20, f: 1, fiber: 6, category: "Produce" },
    { name: "Dahi / Curd Whole Milk (1 cup / 150g)", cals: 100, p: 5, c: 7, f: 5, fiber: 0, category: "Dairy & Eggs" },
    { name: "Goan Fish Curry (1 cup / 200g)", cals: 220, p: 24, c: 6, f: 11, fiber: 1.5, category: "Seafood" },
    { name: "Chicken Breast (Cooked, 150g)", cals: 247, p: 46, c: 0, f: 5.3, fiber: 0, category: "Poultry & Meat" },
    { name: "Chicken Thigh Skinless (Cooked, 150g)", cals: 270, p: 38, c: 0, f: 12, fiber: 0, category: "Poultry & Meat" },
    { name: "Wild Salmon (Cooked, 150g)", cals: 280, p: 35, c: 0, f: 14, fiber: 0, category: "Seafood" },
    { name: "Shrimp (Cooked, 150g)", cals: 151, p: 29, c: 1, f: 2, fiber: 0, category: "Seafood" },
    { name: "Canned Tuna in Water (150g)", cals: 130, p: 28, c: 0, f: 1, fiber: 0, category: "Seafood" },
    { name: "Greek Yogurt 0% (1 cup / 200g)", cals: 130, p: 20, c: 7, f: 0, fiber: 0, category: "Dairy & Eggs" },
    { name: "Cottage Cheese 2% (150g)", cals: 120, p: 18, c: 6, f: 3, fiber: 0, category: "Dairy & Eggs" },
    { name: "Firm Tofu (150g)", cals: 130, p: 15, c: 3, f: 7, fiber: 0.6, category: "Plant Proteins" },
    { name: "Black Beans (Cooked, 1/2 cup / 86g)", cals: 114, p: 7.6, c: 20, f: 0.5, fiber: 7.5, category: "Legumes" },
    { name: "Chickpeas (Cooked, 1/2 cup / 82g)", cals: 134, p: 7.3, c: 22, f: 2.1, fiber: 6.2, category: "Legumes" },
    { name: "Lentils (Cooked, 1/2 cup / 99g)", cals: 115, p: 9, c: 20, f: 0.4, fiber: 7.8, category: "Legumes" },
    { name: "Brown Rice (Cooked, 1 cup / 195g)", cals: 218, p: 4.5, c: 45, f: 1.6, fiber: 3.5, category: "Grains & Starches" },
    { name: "Quinoa (Cooked, 1 cup / 185g)", cals: 222, p: 8.1, c: 39, f: 3.5, fiber: 5.2, category: "Grains & Starches" },
    { name: "Rolled Oats (Dry, 50g)", cals: 190, p: 6.5, c: 34, f: 3.5, fiber: 4.5, category: "Grains & Starches" },
    { name: "Sweet Potato (Baked, 1 medium / 130g)", cals: 112, p: 2, c: 26, f: 0.1, fiber: 3.8, category: "Grains & Starches" },
    { name: "Sourdough Bread (1 slice / 45g)", cals: 110, p: 4, c: 22, f: 0.8, fiber: 1, category: "Bakery" },
    { name: "Avocado (1/2 fruit / 100g)", cals: 160, p: 2, c: 8.5, f: 14.7, fiber: 6.7, category: "Healthy Fats & Produce" },
    { name: "Almond Butter (1 tbsp / 16g)", cals: 98, p: 3.4, c: 3, f: 8.9, fiber: 0.5, category: "Nuts & Spreads" },
    { name: "Peanut Butter Natural (1 tbsp / 16g)", cals: 95, p: 4, c: 3.5, f: 8, fiber: 0.5, category: "Nuts & Spreads" },
    { name: "Banana (Medium, 118g)", cals: 105, p: 1.3, c: 27, f: 0.3, fiber: 3.1, category: "Fruits" },
    { name: "Apple (Medium, 180g)", cals: 95, p: 0.5, c: 25, f: 0.3, fiber: 4.4, category: "Fruits" },
    { name: "Blueberries (1 cup / 148g)", cals: 84, p: 1.1, c: 21, f: 0.5, fiber: 3.6, category: "Fruits" },
    { name: "Olive Oil Extra Virgin (1 tbsp / 14g)", cals: 119, p: 0, c: 0, f: 13.5, fiber: 0, category: "Oils" },
    { name: "Broccoli (Steamed, 1 cup / 150g)", cals: 55, p: 3.7, c: 11, f: 0.6, fiber: 5.2, category: "Vegetables" },
    { name: "Almond Butter (1 tbsp / 16g)", cals: 98, p: 3.4, c: 3, f: 8.9, fiber: 0.5, category: "Nuts & Spreads" },
    { name: "Peanut Butter Natural (1 tbsp / 16g)", cals: 95, p: 4, c: 3.5, f: 8, fiber: 0.5, category: "Nuts & Spreads" },
    { name: "Banana (Medium, 118g)", cals: 105, p: 1.3, c: 27, f: 0.3, fiber: 3.1, category: "Fruits" },
    { name: "Apple (Medium, 180g)", cals: 95, p: 0.5, c: 25, f: 0.3, fiber: 4.4, category: "Fruits" },
    { name: "Blueberries (1 cup / 148g)", cals: 84, p: 1.1, c: 21, f: 0.5, fiber: 3.6, category: "Fruits" },
    { name: "Olive Oil Extra Virgin (1 tbsp / 14g)", cals: 119, p: 0, c: 0, f: 13.5, fiber: 0, category: "Oils" },
    { name: "Broccoli (Steamed, 1 cup / 150g)", cals: 55, p: 3.7, c: 11, f: 0.6, fiber: 5.2, category: "Vegetables" },
    { name: "Spinach (Raw, 2 cups / 60g)", cals: 14, p: 1.7, c: 2.2, f: 0.2, fiber: 1.5, category: "Vegetables" },
    { name: "Mixed Nuts (30g)", cals: 173, p: 5, c: 6, f: 15, fiber: 1.8, category: "Nuts & Spreads" }
  ],

  // Preview Biomarkers & Lab Panel (Clearly marked as Demo / Preview Data)
  biomarkersPreview: [
    {
      marker: "Fasting Blood Glucose",
      value: "88 mg/dL",
      status: "Optimal",
      range: "70 – 99 mg/dL",
      pct: 45,
      category: "Metabolic Health",
      note: "Excellent insulin sensitivity and stable glucose regulation."
    },
    {
      marker: "HbA1c (Glycated Hemoglobin)",
      value: "5.1 %",
      status: "Optimal",
      range: "< 5.7 %",
      pct: 35,
      category: "Metabolic Health",
      note: "Reflects healthy 90-day average blood sugar management."
    },
    {
      marker: "Lipid: Triglycerides / HDL Ratio",
      value: "1.4",
      status: "Optimal",
      range: "< 2.0 (Lower is better)",
      pct: 30,
      category: "Cardiovascular Health",
      note: "Low atherogenic risk and high protective HDL proportion."
    },
    {
      marker: "hs-CRP (High-Sensitivity C-Reactive Protein)",
      value: "0.6 mg/L",
      status: "Low Risk",
      range: "< 1.0 mg/L",
      pct: 20,
      category: "Inflammatory Markers",
      note: "Low systemic inflammation supporting rapid post-exercise recovery."
    },
    {
      marker: "25-Hydroxy Vitamin D3",
      value: "42 ng/mL",
      status: "Sufficient",
      range: "30 – 80 ng/mL",
      pct: 50,
      category: "Micronutrients",
      note: "Supports bone mineral density, immunity, and endocrine balance."
    },
    {
      marker: "Ferritin (Iron Storage)",
      value: "115 ng/mL",
      status: "Normal",
      range: "30 – 300 ng/mL",
      pct: 40,
      category: "Micronutrients",
      note: "Adequate cellular iron stores for optimal oxygen delivery."
    }
  ],

  // Preview Genetic Traits & Nutrigenomics (Clearly marked as Educational Preview)
  geneticsPreview: [
    {
      trait: "CYP1A2 Gene: Caffeine Metabolism",
      variant: "Fast Metabolizer (A/A Allele)",
      category: "Metabolic Speed",
      guidance: "Caffeine is cleared rapidly by the liver. Ergogenic benefits for morning or afternoon workouts with low sleep disruption risk."
    },
    {
      trait: "LCT Gene: Lactose Persistence",
      variant: "Intermediate Lactase Producer",
      category: "Digestive Tolerance",
      guidance: "Tolerates fermented dairy (Greek yogurt, aged cheese, whey isolate) comfortably; moderate whole milk intake."
    },
    {
      trait: "FADS1 Gene: Omega-3 Fatty Acid Synthesis",
      variant: "Low Endogenous Conversion",
      category: "Essential Lipids",
      guidance: "Direct dietary EPA/DHA from wild fish or algal oil is recommended rather than relying solely on plant-based ALA (flax/chia)."
    },
    {
      trait: "VDR Gene: Vitamin D Receptor Affinity",
      variant: "Standard Efficiency",
      category: "Micronutrient Absorption",
      guidance: "Standard baseline absorption. Moderate daily sunlight exposure and 1000-2000 IU maintenance is recommended."
    }
  ],

  // Specialist & Dietitian Network
  specialists: [
    {
      name: "Dr. Elena Rostova, PhD, RD",
      title: "Board-Certified Sports Dietitian (CSSD)",
      specialty: "High-Performance Athletic Nutrition & Body Recomposition",
      location: "San Francisco, CA / Telehealth",
      rating: "4.9 ★ (120+ reviews)",
      bio: "12+ years optimizing nutritional protocols for Olympic athletes, endurance runners, and busy professionals.",
      initials: "ER"
    },
    {
      name: "Marcus Vance, MS, CNS",
      title: "Clinical Nutritionist & Metabolic Coach",
      specialty: "Insulin Resistance, PCOS & Weight Management",
      location: "Austin, TX / Telehealth",
      rating: "5.0 ★ (94 reviews)",
      bio: "Specializes in sustainable, non-restrictive dietary protocols for hormonal balance and fat loss.",
      initials: "MV"
    },
    {
      name: "Dr. Ananya Sharma, MD, FACN",
      title: "Integrative Medicine & Clinical Nutrition",
      specialty: "Cardiometabolic Health & Gut Microbiome",
      location: "New York, NY / Telehealth",
      rating: "4.9 ★ (180+ reviews)",
      bio: "Combines evidence-based clinical nutrition with functional laboratory insights.",
      initials: "AS"
    }
  ]
};
