services:
  - type: web
    name: nutriai-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PORT
        value: 5000
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
